name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
        id: buildx
        with:
          install: true
      - name: Build
        run: |
          docker build --build-arg MATURIN_VERSION=1.8 .
